version: '3'
services:
  client:
    build: ./client
    command: npm start
    volumes:
      - ./client:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
  server:
    build: ./server
    command: npm start
    volumes: 
      - ./server:/usr/src/app
      - /usr/src/app/node_modules
    ports: 
      - "4000:4000"
  db:
    image: mysql
    restart: always
    ports:
      - 3306:3306
    volumes:
      - mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: abc12345
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
volumes:
  mysql:
