export const cartConstant = {
    CLIENT_CREATED: 'CLIENT_CREATED',
    PRODUCTS_FOUND: 'PRODUCTS_FOUND',
    CHECKOUT_FOUND: 'CHECKOUT_FOUND',
    SHOP_FOUND: 'SHOP_FOUND',
    ADD_VARIANT_TO_CART: 'ADD_VARIANT_TO_CART',
    UPDATE_QUANTITY_IN_CART: 'UPDATE_QUANTITY_IN_CART',
    REMOVE_LINE_ITEM_IN_CART: 'REMOVE_LINE_ITEM_IN_CART',
    OPEN_CART: 'OPEN_CART',
    CLOSE_CART: 'CLOSE_CART'
}